<?php

/**
 * @file
 * Test module for Filter module hooks and functions not used in core.
 */

/**
 * Implements hook_filter_format_insert().
 */
/*function filter_test_filter_format_insert($format) {
  drupal_set_message('hook_filter_format_insert invoked.');
}*/

/**
 * Implements hook_filter_format_update().
 */
/*function filter_test_filter_format_update($format) {
  drupal_set_message('hook_filter_format_update invoked.');
}*/

/**
 * Implements hook_filter_format_disable().
 */
/*function filter_test_filter_format_disable($format) {
  drupal_set_message('hook_filter_format_disable invoked.');
}*/

/**
 * Implements hook_filter_info().
 */
function filter_test_filter($op, $delta = 0, $format = -1, $text = '') {
  switch ($op) {
    case 'list':
      return array(0 => t('Filter test replace'));

    case 'process':
      return filter_test_replace($text, $op, $format);

    default:
      return $text;
  }

/*  $filters['filter_test_uncacheable'] = array(
    'title' => 'Uncacheable filter',
    'description' => 'Does nothing, but makes a text format uncacheable.',
    'cache' => FALSE,
  );
  $filters['filter_test_replace'] = array(
    'title' => 'Testing filter',
    'description' => 'Replaces all content with filter and text format information.',
    'process callback' => 'filter_test_replace',
  );
  return $filters;
*/
}

/**
 * Implements callback_filter_process().
 *
 * Process handler for filter_test_replace filter.
 *
 * Replaces all text with filter and text format information.
 */
function filter_test_replace($text, $op, $format, $cache = FALSE) {
  $text = array();
  $text[] = 'Filter: Testing filter';
  $text[] = 'Format: ' . $format;
  //$text[] = 'Language: ' . $langcode;
  $text[] = 'Cache: ' . ($cache ? 'Enabled' : 'Disabled');
  return implode("<br />\n", $text);
}

